package com.example.demo;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RestController;


// Generated by https://start.springboot.io
// 优质的 spring/boot/data/security/cloud 框架中文文档尽在 => https://springdoc.cn
@SpringBootApplication
@RestController
public class ChhengthaiApplication {

	public static void main(String[] args) {
		SpringApplication.run(ChhengthaiApplication.class, args);
	}

	@GetMapping("/api/health")
	public String health() {
		return "OK";
	}
}
